services:
  backend_app:
    build: .
    env_file:
      - .env
    ports:
      - $BACKEND_PORT:$BACKEND_PORT
  
  frontend_streamlit:
    build: 
      context: frontend_streamlit
      dockerfile: Dockerfile
    environment:
      - ENDPOINT_URL=http://backend_app:$BACKEND_PORT
    ports:
      - 8501:8501