services:
  backend_app:
    build: .
    ports:
      - 8080:8080
  
  frontend_streamlit:
    build: 
      context: frontend_streamlit
      dockerfile: Dockerfile
    environment:
      - ENDPOINT_URL=http://backend_app:8080
    ports:
      - 8501:8501