branch-defaults:
  default:
    environment: medical-insurance-charges-frontend-env
    group_suffix: null
global:
  application_name: medical-insurance-charges-frontend-app
  branch: null
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
