name: CI - Linter

on: 
  pull_request:
    paths:
      - backend_app/**
      - frontend_streamlit/**

jobs:
    linter:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Python 3.11
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'

            - name: Ruff linter
              uses: chartboost/ruff-action@v1
              with:
                src: "./backend_app ./frontend_streamlit"
