name: Medical Insurance Charges Prediction - linter

on:
    pull_request: 
        branches:
        - master
        paths: 
        - backend_app
        - frontend_streamlit

jobs:
    ruff:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: chartboost/ruff-action@v1

